name: Build NixOS Configurations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # run the job inside the official Nix Docker image so Nix is already available
    container:
      image: nixos/nix:latest
      # options are optional; running as root inside the container is common
      options: --user root

    strategy:
      fail-fast: false
      matrix:
        config: [laptop, desktop, wsl]

    # make Nix settings available to all steps in the job
    env:
      # point NIX_PATH at the channel you want
      NIX_PATH: "nixpkgs=channel:nixos-unstable"
      # enable flakes and other experimental features via NIX_CONFIG
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        accept-flake-config = true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update flake inputs
        run: |
          nix flake update

      - name: Build NixOS configuration - ${{ matrix.config }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel -L

      - name: Check flake
        if: matrix.config == 'default'
        run: |
          nix flake check -L
        continue-on-error: true

      - name: Show build outputs
        if: success()
        run: |
          echo "✅ Successfully built ${{ matrix.config }} configuration"
          ls -lah result/
